### ISSUE TITLE
Fix card info for Kusama active and waiting validators.

### ISSUE THREAD

**Issue by sahilnanda1995** [prastut/polkaviz#30]
![image](https://user-images.githubusercontent.com/41546731/68125186-f7aae600-ff36-11e9-9d82-79686b71e5bf.png)

**Comment by sahilnanda1995** [comment]
@bhaskarSingh requested changes
- [ ] replacing account id with account index/nickname
- [x] Adding nominators stake and self stake

**Comment by bhaskarSingh** [comment]
What do you mean by account index ?

**Comment by sahilnanda1995** [comment]
> What do you mean by account index ?

![image](https://user-images.githubusercontent.com/41546731/73126764-81210000-3fdc-11ea-80b1-f01f789199e6.png)
above ss from: https://polkadot.js.org/apps/#/staking/
account index in the above image: 43grh, 4kfTq, 4WYy5
`const accounts = await api.derive.accounts.indexes();`
