### ISSUE TITLE
Reduce intentions loading time.

### ISSUE THREAD

**Issue by sahilnanda1995** [prastut/polkaviz#41]
Use the server here to reduce the loading time.
@bhaskarSingh need to discuss with you the current workflow of the polkanalytics-api.

**Comment by bhaskarSingh** [comment]
check commit: f0ccb241638845ce61c1c16ebaf7bf0b83bfe395

**Comment by sahilnanda1995** [comment]
> check commit: [f0ccb24](https://github.com/thevantageproject/polkaviz/commit/f0ccb241638845ce61c1c16ebaf7bf0b83bfe395)

@bhaskarSingh 
Let's follow the following procedure from now on:
1. fixes deployed on a surge domain for easy testing
2. PR to main branch for closing the issues.
